### ISSUE TITLE
Set up local Jekyll instance to preview changes

### ISSUE THREAD

**Issue by danswick** [colleenmcginnis/colleenmcginnis.github.io#2]
Hey @colleenmcginnis, just setting up an issue here so you don't have to comment on your commits :) 

In reference to https://github.com/danswick/colleensite/commit/aac0ff720d676a8ac84eca9dc546d40159ad8595, yes, the reason you can't preview your changes as you make them is that GitHub is hiding a bunch of the core Jekyll stuff from you in the background. 

If you check out [my site](https://github.com/danswick/danswick.github.io) on GitHub, you'll notice a directory that you don't have called `_site`. The reason that directory is there is because I run Jekyll on my local computer in order to preview changes before pushing them up to GitHub. 
### How Jekyll Works

Okay, but why is it like that? Jekyll is more than just templates and config files, it's actually a bit of software that:
1. goes through all of the files in a directory (in this case, all of the files in your colleenmcginnis.github.io repo) 
2. decides which files need to processed 
3. does some processing, including applying whatever template you'd like it to apply
4. copies the resulting files to a new directory 

When I run Jekyll locally, I can see that resulting directory in `_site`, but when GitHub pages runs it for you automatically, all of that file copying business is hidden from you. This keeps your repo tidy, but also sort of obscures what's going on. 
### How to run Jekyll locally

Okay, that's a lot of mumbo-jumbo, but you probably want to actually try the thing out. Just as a heads up, this requires some command line work, so you might want to either reserve a decent chunk of time to get yourself acquainted, or we can work on it together when I'm back in the office. Or both! 

Take a gander at the official Jekyll installation instructions here - http://jekyllrb.com/docs/installation/. Once you've looked that over, take a look at GitHub's documentation, which explains things a bit more plainly and gives you some gh-pages-specific tips - https://help.github.com/articles/using-jekyll-with-pages/. 

The next step is hitting the command line and getting your requirements installed. For that, just go ahead and follow the directions on the [GitHub documentation page](https://help.github.com/articles/using-jekyll-with-pages/) I linked to above. This will probably be confusing at first and definitely made me give up a couple of times. Power through and I am happy to help if you're stuck in a stack-overflow pit of despair! 
### Assume a working local system

Okay, everything's set up, now you just follow the directions in the [GitHub Pages guide](https://help.github.com/articles/using-jekyll-with-pages/)! 
1. cd to the directory you want to serve. `cd colleensite`, for example.
2. Tell Jekyll to build your site and start a local server:
   - `jekyll serve`, or, if you want it to regenerate every time you change a file (I like this one), `jekyll serve --watch`
   - You can also run Jekyll through Bundler. GitHub recommends this, but I've never noticed a difference, possibly because my stuff is always so basic. `bundle exec jekyll serve`. 
3. Point your browser to `http://localhost:4000/`

Okay! See your site? If not, check out some of the previous steps and see if you can parse any error messages in the command line. Tools with lots of Ruby dependencies can sometimes be confusing and frustrating, so don't feel bad if you feel totally lost. If you don't feel angry at all of these weirdly-named programs, you're a champion and have much more patience than I :) 
### Oy

Getting everything set up the first time is a bit of a haul, but I think it's worth it! It's so neat to see it working the first time and it will make you way more comfortable working in the command line, which is super powerful and useful for tons of stuff. If this seems like a lot for 10:30 on a Thursday night, you can always keep pushing your changes up to GitHub for the time being. 

Oh! And here's a post I did after spending way too much time getting all this stuff set up for the first time - http://danswick.com/posts/setup/. 

Keep on keepin' on! 

![andrew wk oh yes](http://media.giphy.com/media/dSatrJNOQUDPa/giphy.gif)

**Comment by colleenmcginnis** [comment]
Noooo @danswick this is what i was afraid of after checking out http://jekyllrb.com/ [that's why i was (pleasantly) surprised and confused that all i had to do was delete from my html files to get the test template to work...] i knew it was too good to be true. 

i had trouble with even understanding command line stuff before i committed to upgrading my OS [when for a split second I foolishly thought I could do without the GitHub desktop version... psssh.]. 

but i will figure it out. too much for a Thursday at 10:30p? if you know me, you know I won't be able to enjoy myself/sleep until I can figure it out [and that nothing is complete without a tina fey reference
http://media.giphy.com/media/xg9dug9ePYiNa/giphy.gif ]

**Comment by danswick** [comment]
:smile: Yeahhhh, sorry it's a bit more complicated. But you're going to be such a command line wizard in no time! 

![TINA FEY GIF HERE](http://media.giphy.com/media/2lB4XWVJLOTh6/giphy.gif)
